# App name & port
spring.application.name=merchant-portal-backend
server.port=8080

# PostgreSQL connection (using default postgres user)
spring.datasource.url=jdbc:postgresql://localhost:5432/merchantdb
spring.datasource.username=postgres
spring.datasource.password=system

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Allow Angular frontend to call backend
spring.web.cors.allowed-origin-patterns=http://localhost:4200
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS

# File upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

# SMTP4Dev mail configuration (smtp4dev default port is 25)
spring.mail.host=localhost
spring.mail.port=25
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.from=no-reply@merchantportal.com

# JWT configuration
# Secret key used to sign and verify JWT tokens (min. 32 characters for HMAC-SHA256)
jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkey
# Token validity duration in milliseconds ? 86400000ms = 24 hours
jwt.expiration=86400000

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
